language:
  - cpp

sudo:
  - true

os:
  - osx

dist:
  - bionic

addons:
  apt:
    packages:
      - libpython2.7-dev

install:
  - sudo pip install -U spacy
  - sudo pip install -U --upgrade cryptography
  - sudo python -m spacy download en_core_web_sm

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make -s
  - ctest --output-on-failure 
